apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongodb
  namespace: testing-env
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      name: mongodb-pod
      labels:
        app: mongo
    spec:
      containers:
        - name: monogodb-container
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: devdb
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: devdb@123
---
#Service Creation for MongoDB
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongo
  ports:
  - port: 27017
    targetPort: 27017


        