apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongopv
  namespace: testing-env
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/nfs_share
    server: 172.31.32.75