apiVersion: v1
kind: ReplicationController
metadata:
  name: maven-webapp-replication-controller
  namespace: testing-env
spec:
  replicas: 1
  selector:
    app: maven-webapp
  template:
    metadata:
      name: maven-webapp-pod
      labels:
        app: maven-webapp
    spec:
      containers:
        - name: maven-webapp-container
          image: dockerhandson/maven-web-application:2
          ports:
            - containerPort: 8080
---
#Service creation
apiVersion: v1
kind: Service
metadata:
  name: maven-webapp-service
  namespace: testing-env
spec:
  type: NodePort
  selector:
    app: maven-webapp
  ports:
    - port: 80
      targetPort: 8080

  