apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nodejs-replicaset
  namespace: testing-env
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      name: nodejs-pod
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app-container
          image: gmk1995/nodejs-app:v1
          ports:
            - containerPort: 9981
---
#Service creation
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
  namespace: testing-env
spec:
  type: NodePort
  selector:
    app: nodejs-app
  ports:
    - port: 80
      targetPort: 9981