apiVersion: v1
kind: ResourceQuota
metadata:
  name: testing-env-resource-quota
  namespace: testing-env
spec:
  hard:
    requests.cpu: "5"
    requests.memory: 10Gi
    limits.cpu: "10"
    limits.memory: 20Gi
    pods: "2"